apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  selector:
    matchLabels:
      run: mywebapp
  replicas: 1
  template:
    metadata:
      labels:
        run: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: eckbalu/mywebapp
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    run: mywebapp
spec:
  ports:
  - port: 80
  selector:
    run: mywebapp
