apiVersion: keda.sh/v1alpha1 
kind: ScaledObject 
metadata: 
  name: prometheus-scaledobject 
  namespace: default 
  labels: 
    name: mywebapp 
spec: 
  scaleTargetRef: 
    name: mywebapp
  pollingInterval: 10 # Optional. Default: 30 seconds 
  cooldownPeriod: 15 # Optional. Default: 300 seconds 
  minReplicaCount: 1 # Optional. Default: 0 
  maxReplicaCount: 10 # Optional. Default: 100 
  triggers: 
    - type: prometheus 
      metadata: 
        # Required 
        serverAddress: 
        metricName: access_frequency 
        threshold: '300'
        query: rate(container_cpu_usage_seconds_total{pod=~"mywebapp-.*", image!="", container_name!="POD"}[2m])
