apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: default
  labels:
    name: mywebapp
spec:
  scaleTargetRef:
    name: mywebapp
  pollingInterval: 10
  cooldownPeriod: 15
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 60
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "40"

