apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: default
  labels:
    name: mywebapp
spec:
  scaleTargetRef:
    name: mywebapp
  pollingInterval: 10 # Optional. Default: 30 seconds 
  cooldownPeriod: 15 # Optional. Default: 300 seconds 
  minReplicaCount: 1 # Optional. Default: 0 
  maxReplicaCount: 10 # Optional. Default: 100 
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 60
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "30"

